INSERT INTO VEHICLERENTAL(ID, FIRSTNAME, LASTNAME, VEHICLETYPE, NUMBEROFDAYS, NAVIGATION, COSTOFRENTAL) VALUES ('1', 'KAREN', 'GREEN', 'ECONOMY', '5', 'TRUE', '500');
INSERT INTO VEHICLERENTAL(ID, FIRSTNAME, LASTNAME, VEHICLETYPE, NUMBEROFDAYS, NAVIGATION, COSTOFRENTAL) VALUES ('2', 'MICHAEL', 'NOONE', 'LUXURY', '2', 'FALSE', '400');
INSERT INTO VEHICLERENTAL(ID, FIRSTNAME, LASTNAME, VEHICLETYPE, NUMBEROFDAYS, NAVIGATION, COSTOFRENTAL) VALUES ('3', 'JAMES', 'DEENEY', 'OTHER', '2', 'FALSE', '100');
INSERT INTO VEHICLERENTAL(ID, FIRSTNAME, LASTNAME, VEHICLETYPE, NUMBEROFDAYS, NAVIGATION, COSTOFRENTAL) VALUES ('4', 'JIM', 'RICHARDS', 'ECONOMY', '5', 'FALSE', '450');
INSERT INTO VEHICLERENTAL(ID, FIRSTNAME, LASTNAME, VEHICLETYPE, NUMBEROFDAYS, NAVIGATION, COSTOFRENTAL) VALUES ('5', 'FIA', 'MACKEL', 'LUXURY', '15', 'TRUE', '2600');
